from polarism.boundary_conditions.absorption.create_absorption_strategy import create_absorption_strategy
from polarism.boundary_conditions.absorption.absorption_mask_strategy import AbsorptionMaskStrategy
from polarism.boundary_conditions.absorption.absorption_cap_strategy import AbsorptionCapStrategy
